In [40]:
import numpy as np

In [41]:
def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

def relu(x):
    return np.maximum(0.0,x)

def relu_derivative(x):
    x[x > 0] = 1
    x[x <= 0] = 0
    return x

class NeuralNetwork:
    def __init__(self, x, y, gamma, nhidden, lr, w1, w2):
        self.input      = x
        self.y          = y
        self.weights1   = w1 #np.random.rand(self.input.shape[1],nhidden) 
        self.weights2   = w2 #np.random.rand(nhidden,self.y.shape[1])
        #self.weights3   = np.random.rand(nhidden,nhidden)
        #self.weights4   = np.random.rand(nhidden,self.y.shape[1])
        self.output     = np.zeros((self.y.shape[0],self.y.shape[1]))
        self.gamma      = gamma
        self.lr         = lr

    def forward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        #self.layer2 = relu(np.dot(self.layer1, self.weights2))
        #self.layer3 = relu(np.dot(self.layer2, self.weights3))
        self.output = np.dot(self.layer1, self.weights2)
        
    def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights
        #d_weights4 = np.dot(self.layer3.T, np.multiply(self.gamma, (2*(self.y - self.output))))
        #d_weights3 = np.dot(self.layer2.T, (np.dot(np.multiply(self.gamma, (2*(self.y - self.output))), self.weights4.T) * relu_derivative(self.layer3)))
        #d_weights2 = np.dot(self.layer1.T, (np.dot((np.dot(np.multiply(self.gamma, (2*(self.y - self.output))), self.weights4.T) * relu_derivative(self.layer3)), self.weights3.T) * relu_derivative(self.layer2)))
        #d_weights1 = np.dot(self.input.T, (np.dot((np.dot((np.dot(np.multiply(self.gamma, (2*(self.y - self.output))), self.weights4.T) * relu_derivative(self.layer3)), self.weights3.T) * relu_derivative(self.layer2)), self.weights2.T) * relu_derivative(self.layer1)))
        d_weights2 = np.dot(self.layer1.T, np.multiply(self.gamma, 2*(self.y - self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot(np.multiply(self.gamma, 2*(self.y - self.output)), self.weights2.T) * sigmoid_derivative(self.layer1)))

        # update weights
        self.weights1 += self.lr*d_weights1
        self.weights2 += self.lr*d_weights2
        #self.weights3 += self.lr*d_weights3
        #self.weights4 += self.lr*d_weights4


In [42]:
# load inp, out
import scipy.io as sio

inf = sio.loadmat("matrics1.mat")
X = inf["mat1_each"]
y = inf["mat2_each"]
gamma = inf["output_each"].T
print(X.shape)
print(y.shape)
print(gamma.shape)
y

(66, 78)
(66, 39)
(66, 1)


array([[ 0.00152217, -0.00175957, -0.00156016, ...,  0.01594208,
        -0.03950794, -0.04524872],
       [-0.00212442,  0.00141891,  0.00264854, ...,  0.00253685,
         0.0552838 , -0.0352833 ],
       [-0.00102743, -0.00138129, -0.00188726, ..., -0.00810148,
        -0.0843131 ,  0.14662646],
       ...,
       [-0.00040489,  0.00060764, -0.00189025, ..., -0.10275028,
        -0.1456727 , -0.10197728],
       [ 0.00250908,  0.00208707, -0.00092389, ...,  0.23969214,
         0.07869303,  0.07850243],
       [ 0.00525217,  0.00441379, -0.00189416, ..., -0.18403281,
         0.08164934, -0.07986213]])

In [43]:
nhidden = 75
w1 = np.random.rand(X.shape[1],nhidden)
w2 = np.random.rand(nhidden,y.shape[1])

nn = NeuralNetwork(X,y,gamma,nhidden,0.001,w1,w2)
for i in range(3000):
    nn.forward()
    nn.backprop()
    
#print error
print(nn.output)


[[0.02812175 0.01499496 0.02025303 ... 0.01955004 0.02362319 0.0217148 ]
 [0.02490817 0.01332187 0.01796275 ... 0.01773422 0.02068147 0.01965966]
 [0.0210213  0.01100471 0.01539368 ... 0.01511974 0.01798245 0.01646851]
 ...
 [0.00162266 0.00089458 0.0011841  ... 0.00139455 0.00130482 0.00148884]
 [0.00078624 0.00049435 0.00067932 ... 0.00082084 0.00070838 0.00077509]
 [0.00145864 0.00076243 0.00104239 ... 0.00118217 0.00111635 0.00120954]]


In [44]:
from numpy import linalg as LA

LA.norm(nn.output-nn.y)

4.5383682757596375

In [45]:
# repeat for all videos in training
for i in range(2,700):
    inf = sio.loadmat("matrics"+str(i)+".mat")
    X = inf["mat1_each"]
    y = inf["mat2_each"]
    gamma = inf["output_each"].T
    w1 = nn.weights1
    w2 = nn.weights2
    nn = NeuralNetwork(X,y,gamma,nhidden,0.001,w1,w2)
    for j in range(3000):
        nn.forward()
        nn.backprop()

KeyboardInterrupt: 

In [39]:
# test one
inf = sio.loadmat("matrics750.mat")
X = inf["mat1_each"]
y = inf["mat2_each"]
gamma = inf["output_each"].T
w1 = nn.weights1
w2 = nn.weights2
## INCOMPLETE 

[-2.00157397e-01 -6.16902433e-02 -3.45475243e-02 -1.57675015e-03
 -1.53240514e-03  1.15457471e-02  2.43484459e-01  2.07913327e-01
  1.08187215e-02  7.59913665e-04  1.20457451e-03 -2.36066466e-02
  6.70210750e-01  2.75559006e-01 -5.89105069e-03  3.12446286e-03
 -3.07466501e-03 -3.45981225e-02  1.04154038e+00  2.32207465e-01
 -5.17111190e-02  3.83151489e-02 -2.15076273e-02 -4.71306145e-02
  1.16275846e+00  1.93481640e-01 -7.04510437e-02  3.39638925e-02
 -2.31558175e-02 -4.43645968e-02  1.79382700e-01  2.16155640e-01
 -1.23497353e-02  3.00150708e-03 -6.00523316e-04 -2.81024162e-02
  5.64871356e-01  2.78847196e-01 -2.95304001e-02  3.05345075e-03
 -5.47498683e-03 -3.95017131e-02  7.69526767e-01 -1.07864049e-01
 -1.14831054e-01 -1.27766181e-03 -1.85960420e-02 -1.99233756e-04
  8.68585071e-01 -1.68582639e-01 -1.62088863e-01 -8.24590524e-03
 -2.38097474e-02  6.04259660e-03  1.27322163e+00  1.74919459e-01
 -8.92698582e-02  4.35922183e-02 -4.76884893e-02 -3.35781506e-02
  1.18990675e+00  2.04269

In [46]:
# write output to file
## INCOMPLETE

[[5 6]]
